/**
 * Reads one wire golden fixture pair — `<name>.bin` and `<name>.json` under
 * this directory — for a vitest to decode and deep-equal (ruling R236).
 *
 * Both files are generated by the engine (`idl-rs docs wire`,
 * `core/src/wire_golden.rs`); nothing here writes them. Node's `fs`, not
 * `import`, so the binary bytes are read verbatim rather than passed
 * through a JSON/JS module transform.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const GOLDEN_DIR = dirname(fileURLToPath(import.meta.url));

/** One decoded fixture: the raw bytes as an `ArrayBuffer` (ready for a
 *  decoder that expects one, same as a real `invoke()` response) and the
 *  parsed expectation JSON. */
export interface WireFixture {
  bin: ArrayBuffer;
  json: Record<string, unknown>;
}

/** Loads `<name>.bin`/`<name>.json` from `app/src/ipc/golden/`. */
export function loadFixture(name: string): WireFixture {
  const bytes = readFileSync(join(GOLDEN_DIR, `${name}.bin`));
  // A `Buffer`'s own `.buffer` is a pooled `ArrayBuffer` that may be larger
  // than the read and share space with other reads — slice to the exact
  // byte range so a decoder sees exactly this fixture's bytes.
  const bin = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  const json = JSON.parse(readFileSync(join(GOLDEN_DIR, `${name}.json`), "utf-8"));
  return { bin, json };
}
