/**
 * Node → chart, in either of decision 83's two gestures — an output-port
 * drag into the notebook column, or the card's chart button ⇒ chart-type
 * selector (idl0 pictograms) — both converge on the same pure operation:
 * append a new `js` cell generated by `plotForm/generate.ts`, charting the
 * node by name. No `id=` attribute is written (C2 §2.2's "Assignment":
 * a fence with none gets one from Rust the next time the document parses —
 * `cells.ts`'s own doc comment records this as the write-path convention),
 * so this module never has to mint one client-side.
 *
 * **§3.6.6 enforcement, honestly bounded.** A rank ≥ 2 value that is not a
 * `spectrogram(...)` call should offer decision 58's "reduce it first"
 * slot, not a chart. This module can only tell a chartable rank-≤1 value
 * (`portShape.ts`'s `"[]"`/`"[t]"`) and a literal `spectrogram(...)` call
 * apart from everything else — it has no way to *positively* detect
 * "rank ≥ 2" until `core` implements the real C2 §3.6 shape (the survey's
 * own gap list item 1; `spectrogram` itself is still a `NotImplemented`
 * stub). `chartEligibilityFor` therefore returns `"unknown"` rather than
 * `"reduce-first"` for everything else — reporting an unresolvable
 * question honestly rather than guessing the answer is exactly §3.7.4's
 * own rule for a port shape, applied here to a chart eligibility decision
 * (see the lane's report for what this means the "reduce it first" slot
 * cannot yet do).
 */

import { generate } from "../plotForm/generate";
import type { MarkProps, PlotProps } from "../plotForm/types";
import type { MathExprCall } from "../model/mathExpr";
import type { PortShape } from "./portShape";

/** Whether a card's chart button should offer a normal chart, the one
 *  raster exception (§3.6.6), or nothing yet. See the module doc comment
 *  for why `"unknown"` is not the same claim as "reduce it first". */
export type ChartEligibility = "chart" | "spectrogram" | "unknown";

/**
 * Decides what a node's chart button offers, from its port shape and its
 * outer call (both already computed by `GraphCanvas.tsx` for the card
 * itself — this function derives nothing new from the definition, it only
 * decides). See the module doc comment.
 */
export function chartEligibilityFor(shape: PortShape, call: MathExprCall | null): ChartEligibility {
  if (call !== null && call.name === "spectrogram") return "spectrogram";
  if (shape === "[]" || shape === "[t]") return "chart";
  return "unknown";
}

/**
 * Appends a new time-cell `js` cell charting `nodeName` with mark type
 * `mark`, generated by `plotForm/generate.ts` — never hand-assembled text,
 * so the result always round-trips through `plotForm/parse.ts` exactly
 * like a Properties-form-authored cell would (C2 §5.3). No `id=` attribute
 * (see the module doc comment); no other byte of `markdown` is touched.
 * This is the "chart button" gesture's whole pure half — the port-drag
 * gesture (decision 83's other one) calls the same function once the drop
 * target and mark choice are known.
 *
 * **Placement, a deliberate simplification.** The new cell is appended at
 * the document's end, never inserted next to the node's own cell or at a
 * drop position — a real "insert near here" placement is `Notebook/
 * index.tsx`'s to decide (it already knows cursor/scroll position; this
 * module does not), and is flagged as unimplemented rather than guessed.
 */
export function insertChartCell(markdown: string, nodeName: string, mark: MarkProps["mark"]): string {
  const props: PlotProps = { chart: "time", marks: [{ channel: nodeName, mark }] };
  const code = generate(props);
  const separator = markdown.length === 0 || markdown.endsWith("\n") ? "" : "\n";
  return `${markdown}${separator}\`\`\`js\n${code}\n\`\`\`\n`;
}
